### ISSUE TITLE
What is this If condition supposed to be doing in integrate()?

### ISSUE THREAD

**Issue by Brennan1994** [HenryGeorgist/fda-model#26]
I'm locally failing my integration test because of this if condition. What's the purpose of it? 

https://github.com/HenryGeorgist/fda-model/blob/ebfcc71321c6643f4954d7d29e99ee68be59ccd4/fda-model/paireddata/PairedData.cs#L75

**Comment by HenryGeorgist** [comment]
well this integrate is kinda specialized. I am integrating probability from 0 to 1, this logic is checking to see if the last probability was strictly zero (since we typically do not estimate the noah event it is almost always the case that this is activated). What i do is i calculate the rectangle from the last probability to 0 (or 1) and add that area (no projection of the shape of the line because we dont know what the extrapolation should do except not decrease...

**Comment by HenryGeorgist** [comment]
I think i pulled this from go-fda: https://github.com/HenryGeorgist/go-fda/blob/main/expectedannualdamage/expectedannualdamage_test.go

specifically from go-consequences:https://github.com/USACE/go-consequences/blob/c7b4a9fe1e1ff392ba7041f3293616c4c58cbb46/compute/simulation.go#L17
and then a test here:
https://github.com/USACE/go-consequences/blob/c7b4a9fe1e1ff392ba7041f3293616c4c58cbb46/compute/simulation_test.go#L20
